# Generated by Django 3.2.13 on 2022-05-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_tempzakladkaforcourier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempzakladkaforcourier',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tempzakladkaforcourier',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='zakladka',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='zakladka',
            name='longitude',
        ),
    ]
