# Generated by Django 3.2.13 on 2022-05-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_auto_20220522_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.city', verbose_name='Город'),
        ),
    ]
