# Generated by Django 3.2.13 on 2022-05-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_auto_20220522_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='klad_type',
            field=models.CharField(choices=[('SNOW', 'Снежный прикоп'), ('MAGNET', 'Магнит'), ('HIDE', 'Тайник'), ('GROUND', 'Прикоп'), ('OTHER', 'Другой')], default='GROUND', max_length=6, verbose_name='Тип клада'),
        ),
        migrations.AlterField(
            model_name='tempzakladkaforcourier',
            name='klad_type',
            field=models.CharField(blank=True, choices=[('SNOW', 'Снежный прикоп'), ('MAGNET', 'Магнит'), ('HIDE', 'Тайник'), ('GROUND', 'Прикоп'), ('OTHER', 'Другой')], default='GROUND', max_length=6, null=True, verbose_name='Тип клада'),
        ),
        migrations.AlterField(
            model_name='zakladka',
            name='klad_type',
            field=models.CharField(choices=[('SNOW', 'Снежный прикоп'), ('MAGNET', 'Магнит'), ('HIDE', 'Тайник'), ('GROUND', 'Прикоп'), ('OTHER', 'Другой')], default='GROUND', max_length=6, verbose_name='Тип клада'),
        ),
    ]
